name: Mmomain
version: 1.0-SNAPSHOT
main: com.ultraplugins.mmomain.Mmomain
api-version: 1.16
authors: [ Shadow501pl, Willikonk ]

commands:
  resource:
    usage: /resource
  weapon:
    usage: /weapon